In [1]:
import numpy as np

In [3]:
np.zeros((3, 2), dtype = 'int16')

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int16)

In [4]:
np.ones((3, 2), dtype = 'int16')

array([[1, 1],
       [1, 1],
       [1, 1]], dtype=int16)

In [6]:
massiv = np.full((3, 2), 10, dtype = 'int16')
massiv

array([[10, 10],
       [10, 10],
       [10, 10]], dtype=int16)

In [7]:
np.full_like(massiv, 5)

array([[5, 5],
       [5, 5],
       [5, 5]], dtype=int16)

In [8]:
np.random.rand(5, 2)

array([[0.80796781, 0.12211869],
       [0.80224025, 0.2772054 ],
       [0.92697691, 0.97730208],
       [0.23157063, 0.50489841],
       [0.44561737, 0.47368709]])

In [15]:
np.random.randint(2, 10, size = (5, 2))

array([[6, 7],
       [4, 6],
       [6, 4],
       [7, 4],
       [6, 8]])

In [16]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [17]:
alt_massiv = np.array([[3, 5, 7]])
np.repeat(alt_massiv, 5, axis = 0)

array([[3, 5, 7],
       [3, 5, 7],
       [3, 5, 7],
       [3, 5, 7],
       [3, 5, 7]])