In [1]:
import numpy as np

In [13]:
massiv = np.array([1, 2, 3])
massiv2 = np.array([4, 5, 6])
massiv2

array([4, 5, 6])

In [8]:
massiv + 5

array([6, 7, 8])

In [9]:
massiv - 3

array([-2, -1,  0])

In [10]:
massiv * 7

array([ 7, 14, 21])

In [11]:
massiv / 2

array([0.5, 1. , 1.5])

In [12]:
massiv ** 4

array([ 1, 16, 81])

In [14]:
massiv + massiv2

array([5, 7, 9])

In [15]:
massiv2 - massiv

array([3, 3, 3])

In [16]:
massiv * massiv2

array([ 4, 10, 18])

In [17]:
massiv2/massiv

array([4. , 2.5, 2. ])

In [18]:
np.sin(np.pi/2)

1.0

In [19]:
np.cos(np.pi/2)

6.123233995736766e-17

In [20]:
import math
math.floor(6.123233995736766e-17)

0

In [26]:
matris = np.full((3, 4), 5)
matris2 = np.full((4, 3), 4)
yeni_matris = np.matmul(matris, matris2)

In [27]:
np.linalg.det(yeni_matris)

0.0

In [33]:
ikid_matris = np.array([[1, 2, 3], [4, 5, 6]])
np.min(ikid_matris, axis = 1)
np.max(ikid_matris, axis = 1)
np.sum(ikid_matris, axis = 1)

array([ 6, 15])